languageCode = "en"
languageName = "English"
weight       = 1
title        = "Brad Kreider"

[params]
  displayName = "EN"
  isoCode     = "en"
  rtl         = false
  dateFormat  = "January 2, 2006"
  description = "Brad Kreider."

[params.author]
  name     = "Brad Kreider"
  image    = "img/avatar.jpg"
  headline = "Data and Computer Science Student"
  bio      = "Messiah University"
  links    = [
    { github   = "https://github.com/bradley-kreider" },
{ linkedin = "https://www.linkedin.com/in/bradleykreider/" },
  ]
